### ISSUE TITLE
Bug en año de nacimiento

### ISSUE THREAD

**Issue by juliodelfos** [wachunei/imprimepase.app#7]
Hola, **muchas gracias por esta herramienta**.

Hice la prueba con mi PdM y encontré un pequeño bug en el año de nacimiento. En vez de colocar el año como 1994, se puso como 0994. [Dejo imagen de referencia](https://imgur.com/a/f4XqAKM).

**Comment by wachunei** [comment]
Hola Julio, gracias por reportar, voy a revisar el bug. Me serviría mucho si me pudieras compartir tu PDF para reproducir el bug, gracias!

**Comment by wachunei** [comment]
Arreglado en #8
